name: Build
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Set up repo
      run: |
        git clone --single-branch --branch windows-support https://gitlab.haskell.org/haskell/ghcup-hs
    - uses: haskell/actions/setup@v1
      id: setup-haskell
      with:
        ghc-version: '8.10.4'
        cabal-version: '3.4'
    - uses: actions/cache@v2
      with:
        path: ${{ steps.setup-haskell.outputs.cabal-store }}
        key: cabal-${{ github.sha }}
        restore-keys: cabal-

    - name: Build
      run: |
        cd ghcup-hs
        cabal build exe:ghcup

    - name: Prepare artifacts
      shell: bash
      run: |
        mkdir -p artifacts
        cp $(find ghcup-hs/dist-newstyle -name ghcup.exe -type f) artifacts/
    - uses: actions/upload-artifact@v2
      with:
        name: ghcup-win
        path: artifacts
